name: cloud_front_release

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

  workflow_dispatch:

env:
  S3_BUCKET_NAME: paragons3front
  AWS_REGION: ap-northeast-2
  CLOUD_FRONT_ID: E1BH7EI7H8L4D0
  REACT_APP_GOOGLE_MAP_KEY: ${{ secrets.REACT_APP_GOOGLE_MAP_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install
        # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Add Environment Variable for Production
        run: |
          echo "REACT_APP_GOOGLE_MAP_KEY=$REACT_APP_GOOGLE_MAP_KEY" >> .env.production

      # - run: npm test --if-present

      - name: Run server build
        run: npm run build
        env:
          CI: ''

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: upload binary to S3
        run:  aws s3 cp --recursive --region ap-northeast-2 build s3://${{ env.S3_BUCKET_NAME }}
          
      - name: Clear Cache to Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*"

      
